databases: 
  name: Code_Connect
  databaseName: Code_Connect
  user: Code_Connect
  plan: free

services:
  type: web
  name: Code_Connect
  runtime: ruby
  plan: free
  buildCommand: "./bin/render-build.sh"
  startCommand: "bundle exec rails server"
  build:
    - bundle exec rails assets:precompile
    - bundle exec rails turbo:compile
  envVars:
    key: DATABASE_URL
    fromDatabase:
      name: Code_Connect
      property: connectionString
    key: RAILS_MASTER_KEY
    sync:false key: WEB_CONCURRENCY
    value: 2  