default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: dpg-cqhv8qks1f4s73ao52fg-a
  port: 5432
  username: code_connect_user
  password: vVeiWcRn4a2Ve8PqPg42jPRO358eTr3s

development:
  <<: *default
  database: Code_Connect_development
  
test:
  <<: *default
  database: Code_Connect_test

production:
  <<: *default
  database: code_connect
  username: code_connect_user
  password: vVeiWcRn4a2Ve8PqPg42jPRO358eTr3s
